### ISSUE TITLE
这不就是Jessibuca Pro的体验版代码嘛

### ISSUE THREAD

**Issue by bosscheng** [EasyDarwin/EasyPlayer.js#235]
对比的仓库地址：https://github.com/langhuihui/jessibuca/tree/v3/demo/public/pro/js  

里面的js 简直一模一样，就把名字改了下而已。

另外，体验版在wasm 里面做了限制，只会解码1个小时。请谨慎使用。

官网：https://jessibuca.com/

github：https://github.com/langhuihui/jessibuca/tree/v3

**Comment by tjlbj** [comment]
easyplayer.js没有一个小时的限制

**Comment by bosscheng** [comment]
@tjlbj 你走软解码试试看，我看了js部分的代码，他是直接把js部分的水印和一小时的检测机制去掉了，但是wasm部分的他是没办法去，可以试试走wasm解码。一个小时候，画面就会暂停不动的。

**Comment by rednettle2614** [comment]
还能这样？？？有什么其他播放器推荐吗

**Comment by rednettle2614** [comment]
还能这样？？5.x呢
